/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

import Link from "next/link";
import React from "react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Link
          className="text-center border-2 border-black px-4 rounded-full mt-2 dark:border-white"
          href={{
            pathname: "/user",
          }}
        >
          <p>My info</p>
        </Link>

        <Link
          className="text-center border-2 border-black px-4 rounded-full mt-2 dark:border-white"
          href={{
            pathname: "/rooms",
          }}
        >
          <p>My rooms</p>
        </Link>
        {children}
      </body>
    </html>
  );
}
